version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgresql_bkp
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test-admin-user 
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups

volumes:
  postgres_data:
  postgres_backups:
